# Configuration for project beam, connector BEAM

# Learn more about the Teamscale IDE Configuration File Format at
# <https://docs.teamscale.com/reference/teamscale-toml/>.

version = "1.0"

root = true

[server]
url = "https://teamscale.laugenstulle.xyz/"

[project]
id = "beam"
